CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id VARCHAR(80) NOT NULL UNIQUE,
  event_type VARCHAR(80) NOT NULL,
  source_service VARCHAR(80) NOT NULL,
  trace_id VARCHAR(120),
  actor_type VARCHAR(40),
  actor_id BIGINT,
  action VARCHAR(80) NOT NULL,
  resource_type VARCHAR(80),
  resource_id VARCHAR(120),
  outcome VARCHAR(20) NOT NULL DEFAULT 'SUCCESS',
  detail_json TEXT,
  occurred_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_log_action_time ON audit_log(action, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_actor_time ON audit_log(actor_type, actor_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_resource ON audit_log(resource_type, resource_id);
