CREATE TABLE IF NOT EXISTS registration_order (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no VARCHAR(64) NOT NULL UNIQUE,
  registration_id BIGINT NOT NULL,
  owner_patient_id BIGINT NOT NULL,
  subject_type VARCHAR(20) NOT NULL,
  subject_id BIGINT NOT NULL,
  amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
  payment_status VARCHAR(20) NOT NULL,
  payment_method VARCHAR(30),
  paid_at TIMESTAMP,
  closed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_registration_order_registration ON registration_order(registration_id);
CREATE INDEX IF NOT EXISTS idx_registration_order_owner_subject ON registration_order(owner_patient_id, subject_type, subject_id, payment_status);
