server:
  port: ${SERVER_PORT:8090}

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  cache:
    type: redis
    redis:
      time-to-live: ${REDIS_CACHE_TTL:10m}

management:
  health:
    redis:
      enabled: ${REDIS_HEALTH_ENABLED:false}
