export const patientRouteWhitelist = new Set([
  "patient-home",
  "patient-dashboard",
  "patient-triage",
  "patient-doctors",
  "patient-appointments",
  "patient-records",
  "patient-prescriptions",
  "patient-reports",
  "patient-invoices",
  "patient-messages",
  "patient-profile",
  "patient-visitors",
  "public-search",
  "public-departments",
  "public-conditions",
  "public-guide",
  "public-research",
  "service-internet-clinic",
  "service-exam-booking",
  "service-inpatient",
  "service-emergency",
  "service-international",
  "doctor-experts",
  "doctor-centers",
  "doctor-schedules",
  "library-symptoms",
  "library-drugs",
  "library-tests",
  "library-rehab",
  "library-articles",
  "ai-symptom",
  "ai-record-summary",
  "ai-medication",
  "ai-assessment",
  "about-hospital",
  "about-news",
  "about-careers",
  "about-contact",
]);

export function isAllowedRoute(routeName = "") {
  return patientRouteWhitelist.has(routeName);
}

export const isAllowedPatientRoute = isAllowedRoute;
