CREATE TABLE IF NOT EXISTS patient (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  phone VARCHAR(20) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  gender VARCHAR(10),
  age INT,
  allergy_history VARCHAR(500),
  past_history VARCHAR(1000),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS department (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(50) NOT NULL UNIQUE,
  description VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS doctor (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  phone VARCHAR(20) UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  department_id BIGINT NOT NULL,
  title VARCHAR(50),
  specialty VARCHAR(500),
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS registration (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL,
  doctor_id BIGINT NOT NULL,
  department_id BIGINT NOT NULL,
  triage_record_id BIGINT,
  appointment_time TIMESTAMP NOT NULL,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS triage_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL,
  chief_complaint TEXT NOT NULL,
  recommended_department VARCHAR(100),
  recommended_doctor_ids VARCHAR(255),
  reason TEXT,
  ai_result_json TEXT,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS medical_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL,
  doctor_id BIGINT NOT NULL,
  registration_id BIGINT NOT NULL UNIQUE,
  chief_complaint TEXT NOT NULL,
  present_illness TEXT,
  past_history TEXT,
  physical_exam TEXT,
  diagnosis TEXT NOT NULL,
  treatment_advice TEXT,
  ai_generated BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prescription (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL,
  doctor_id BIGINT NOT NULL,
  medical_record_id BIGINT,
  risk_level VARCHAR(20),
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prescription_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prescription_id BIGINT NOT NULL,
  drug_name VARCHAR(100) NOT NULL,
  dosage VARCHAR(100) NOT NULL,
  frequency VARCHAR(100) NOT NULL,
  usage_method VARCHAR(200) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prescription_check_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prescription_id BIGINT,
  patient_id BIGINT NOT NULL,
  doctor_id BIGINT NOT NULL,
  risk_level VARCHAR(20) NOT NULL,
  suggestions TEXT,
  interactions TEXT,
  ai_result_json TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notification_message (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doctor_id BIGINT NOT NULL,
  patient_id BIGINT,
  prescription_id BIGINT,
  type VARCHAR(50) NOT NULL,
  title VARCHAR(100) NOT NULL,
  content TEXT NOT NULL,
  risk_level VARCHAR(20),
  read_status VARCHAR(20) NOT NULL DEFAULT 'UNREAD',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prompt_template (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_type VARCHAR(50) NOT NULL,
  department_code VARCHAR(50),
  template_name VARCHAR(100) NOT NULL,
  template_content TEXT NOT NULL,
  output_schema TEXT,
  version VARCHAR(20) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_generation_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_type VARCHAR(50) NOT NULL,
  biz_id BIGINT,
  patient_id BIGINT,
  doctor_id BIGINT,
  prompt_template_id BIGINT,
  request_summary TEXT,
  response_summary TEXT,
  raw_result_json TEXT,
  status VARCHAR(20) NOT NULL,
  error_message TEXT,
  duration_ms INT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(50) NOT NULL,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS drug (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  specification VARCHAR(100),
  contraindication TEXT,
  interaction_rule TEXT,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS knowledge_entry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  symptoms TEXT NOT NULL,
  risk_signals TEXT,
  advice TEXT NOT NULL,
  department_code VARCHAR(50),
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO department (id, code, name, description) VALUES
  (1, 'CARDIOLOGY', '心内科', '心血管疾病诊疗科室'),
  (2, 'GENERAL', '全科/轻症门诊', '校园常见轻症初诊与复诊')
ON CONFLICT (id) DO NOTHING;

INSERT INTO doctor (id, name, phone, password_hash, department_id, title, specialty, status) VALUES
  (1, '张医生', '13900000001', '{plain}123456', 1, '主任医师', '胸痛、心悸、高血压', 'ENABLED'),
  (2, '李医生', '13900000002', '{plain}123456', 2, '主治医师', '感冒发热、咽痛、腹泻、皮肤过敏', 'ENABLED')
ON CONFLICT (id) DO NOTHING;

INSERT INTO admin_user (id, username, password_hash, name, status)
VALUES (1, 'admin', '{plain}123456', '系统管理员', 'ENABLED')
ON CONFLICT (id) DO NOTHING;

INSERT INTO drug (id, name, specification, contraindication, interaction_rule, status) VALUES
  (1, '阿司匹林', '100mg', '活动性出血禁用', '与抗凝药同用出血风险升高', 'ENABLED'),
  (2, '对乙酰氨基酚', '0.5g', '严重肝功能不全慎用', '避免与其他含对乙酰氨基酚复方药重复使用', 'ENABLED')
ON CONFLICT (id) DO NOTHING;

INSERT INTO knowledge_entry (id, title, symptoms, risk_signals, advice, department_code, status) VALUES
  (1, '普通感冒', '鼻塞、流涕、咽痛、低热、轻微咳嗽', '持续高热、呼吸困难、胸痛、意识异常', '注意休息和补液，症状加重或超过三天建议线下就诊。', 'GENERAL', 'ENABLED'),
  (2, '急性腹泻', '腹泻、腹痛、恶心、轻度乏力', '便血、严重脱水、持续高热、剧烈腹痛', '补液和清淡饮食，出现危险信号时及时就医。', 'GENERAL', 'ENABLED')
ON CONFLICT (id) DO NOTHING;
